### ISSUE TITLE
Notice about pear and some packages

### ISSUE THREAD

**Issue by tommy-muehle** [rafaelfelix/puppet-phpqatools#7]
Hi Rafael,

i get noticed to this module over https://github.com/dirkaholic/vagrant-php-dev-box. 
and i want to inform you that some packages like phpunit are no longer availabe over pear in future.
see this link for more informations: 

https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method

so you want perhaps overwork this module.

best regards.
tommy

**Comment by rafaelfelix** [comment]
Tommy,

Thanks a lot for the heads up. I'll refactor the module to install the
phpunit using the phar file rather than PEAR. Fortunately, we still have
until December to do this... because I'll not have time within this month.

Thanks for using my module in your open source project! I'll use it myself.

Best regards,
Rafael Felix Correa

**Comment by HMAZonderland** [comment]
It might even be better to switch to Composer.
